fix(unity-bootstrap-theme): added container within navbar in examples
ASU/asu-unity-stack pull request #1015
Opened 2023-04-18 08:22 UTC by davidornelas11

### Description
Containers are now supposed to be within `.navbar` classes. This is to simplify new css.
Mobile and desktop yellow underline on dropdowns did not come up anymore.
SVG's were not transforming on active

### Links

- [JIRA ticket](https://asudev.jira.com/browse/UDS-1321?atlOrigin=eyJpIjoiOTkzODc3N2Q5YTZmNGZjZGI1ZmY3MTliNmZkMDczYTEiLCJwIjoiaiJ9)

### Checklist

- [x] Unity project successfully builds from root `yarn install` & `yarn build`
- [x] Commits do not contain multiple scopes
- [x] Add/updated examples
- [x] No new console errors
- [x] Accessibility checks

### Browsers

- [x] Chrome
- [x] Safari
- [x] Firefox
- [x] Edge

2023-04-18 12:03 UTC, maycomayco requested changes
**In mobile view, I found the following errors:** 
- The SVG doesn't apply the transformation CSS rule to rotate 180deg when the dropdown is opened
- I couldn't see the yellow bottom border for the open dropdown 

![image](https://user-images.githubusercontent.com/1083822/232771123-030fad63-01cb-44d7-a887-00039f8e23b3.png)

### Prod version
![image](https://user-images.githubusercontent.com/1083822/232771333-c9f178f6-5657-41f6-a97b-920da8cc74f3.png)

2023-04-18 12:10 UTC, maycomayco commented
**In desktop view, I found the following errors:** 
- The SVG doesn't apply the transformation CSS rule to rotate 180deg when the dropdown is opened (same as mobile)
- when the item is active we should keep the hover status also (yellow bottom bar)

![image](https://user-images.githubusercontent.com/1083822/232772085-22ddfe6b-f741-4831-a461-241ec2ce54ec.png)

### Prod version
(Item without hover, only active)
![image](https://user-images.githubusercontent.com/1083822/232772894-3857c11b-eb54-4686-8f67-c6fc6fbf47eb.png)

2023-04-19 04:21 UTC, davidornelas11 commented on packages/unity-bootstrap-theme/src/scss/extends/_global-header.scss
> +    &:has(.nav-link.show)::after {
Desktop yellow line on dropdown menu

2023-04-19 04:21 UTC, davidornelas11 commented on packages/unity-bootstrap-theme/src/scss/extends/_global-header.scss
> +      &:has(.nav-link.show)::after {
Mobile yellow line on dropdown menu

2023-04-19 04:23 UTC, davidornelas11 commented on packages/unity-bootstrap-theme/stories/organisms/global-header/global-header.templates.stories.js
> +                        <div class="nav-item dropdown megamenu header-dropdown-3">
removed active class because it should be added when clicking a menu item, not as a default

2023-04-28 14:05 UTC, maycomayco commented on packages/unity-bootstrap-theme/src/scss/extends/_global-header.scss
> +    &:has(.nav-link.show)::after {
According to the documentation, the `:has()` pseudo-class is not supported in any versions of Firefox and IE 
https://caniuse.com/css-has

2023-04-28 14:07 UTC, maycomayco commented on packages/unity-bootstrap-theme/src/scss/extends/_global-header.scss
> +      &:has(.nav-link.show)::after {
Same as above

2023-04-28 14:12 UTC, maycomayco commented on packages/unity-bootstrap-theme/stories/organisms/global-header/global-header.templates.stories.js
> +                        <div class="nav-item dropdown megamenu header-dropdown-3">
BS5 requires the `active` class in `.nav-item` element, could we check this?

2023-05-02 00:09 UTC, scott-williams-az commented
With the latest changes, it matches what we currently have with BS4. LGTM to me

2023-05-02 14:52 UTC, maycomayco approved these changes
LGTM 👏

2023-05-02 19:33 UTC, merged