Uds 1411 - Cards need to have links in titles
ASU/asu-unity-stack pull request #1087
Opened 2023-06-08 23:28 UTC by davidornelas11

### Description
Cards need to have titles that are links

Titles on cards for events and news now have links in the titles

### Links

- [JIRA ticket](https://asudev.jira.com/browse/UDS-1411?atlOrigin=eyJpIjoiY2QyNjA5ZmVlMzNmNGVjNTg0Yzc5ZDhhMThlYjllY2YiLCJwIjoiaiJ9))

### Checklist

- [x] Unity project successfully builds from root `yarn install` & `yarn build`
- [x] Commits do not contain multiple scopes
- [x] Add/updated examples
- [x] No new console errors
- [x] Accessibility checks

2023-06-12 22:08 UTC, mlsamuelson reviewed
For `component-events` we need to be using the `alias` field for the event title's link. We can't count on the rsvp links to be there.

2023-06-12 22:22 UTC, mlsamuelson commented on packages/component-carousel/src/components/CardCarousel/index.js
> +      linkUrl={linkUrl || buttons?.[0]?.href}
@davidornelas11 I debated on whether this update belonged in here, but after testing, seeing that it brings the behavior in-line for the header link regarding the "read more" `linkUrl` and the `buttons`, I think ultimately it makes sense. Good call.

2023-06-12 22:51 UTC, mlsamuelson requested changes

2023-06-12 22:51 UTC, mlsamuelson commented on packages/components-core/src/components/Card/index.js
> +  {console.log(linkUrl, linkLabel)}
`console.log()`

2023-06-13 14:09 UTC, mlsamuelson requested changes
@davidornelas11 Still needs work. We should be using using the `alias` field for the event title's link in `component-events`. We can't count on the rsvp links to be there - instead we should be linking to the `alias` which is the url for the event, so it'll always be there.

2023-06-13 21:12 UTC, davidornelas11 commented on packages/component-events/src/core/transformers/data.transfromer.js
> +  alias: data.node.alias, // Also used for card link in title of card
Kept this the same, only added a comment for clarity on how we use it

2023-06-13 21:19 UTC, davidornelas11 commented on packages/component-news/src/components/CardGridNews/index.js
> +      cardLink={feed.alias}
matches what we do in component-events, but uses alias without the date, which does not seem to be available for news data

2023-06-13 22:15 UTC, scott-williams-az approved these changes

2023-06-13 23:06 UTC, mlsamuelson approved these changes

2023-06-13 23:06 UTC, merged