docs(unity-bootstrap-theme): align old stories with the new figma design for the hero component
ASU/asu-unity-stack pull request #1094
Opened 2023-06-16 20:17 UTC by maycomayco

### Description

We aligned the existing stories in the storybook with the new design for the hero component

### Links

- [Unity reference site](https://unity.web.asu.edu/)
- [JIRA ticket](https://asudev.jira.com/browse/UDS-1304)
- [Unity Design Kit OLD](https://xd.adobe.com/view/56f6cb78-9af5-4b12-b4ce-ef319f71113f-03a5/screen/2507e745-04a5-495a-a49a-f8f6bd82c155)
- [Unity Design Kit NEW](https://xd.adobe.com/view/78cbcd93-ef3e-4153-a7c5-428baae21ed1-2d98/)

### Checklist

- [x] Unity project successfully builds from root `yarn install` & `yarn build`
- [x] Commits do not contain multiple scopes
- [x] Add/updated examples
- [x] No new console errors
- [x] Accessibility checks

### Browsers

- [x] Chrome
- [x] Safari
- [x] Firefox
- [x] Edge

### Images
![image](https://github.com/ASU/asu-unity-stack/assets/1083822/c908fba6-93b5-4961-82fe-d35c8c1bdeb0)

2023-06-28 01:31 UTC, davidornelas11 submitted a review, later dismissed
Looks good!

2023-06-29 14:27 UTC, mlsamuelson requested changes
@maycomayco Comparing the stories with the XD, I don't see a `Story Hero Medium` story  - were you considering that outside the scope? If so, can you create a separate ticket so we have an example for that, please?

2023-06-29 14:27 UTC, mlsamuelson commented on packages/unity-bootstrap-theme/stories/molecules/heroes/heroes.examples.stories.js
> +        ASU named to prestigious university association
We need less words in this hero for the example. 3-4 words would be ideal - maybe "ASU named prestigious university".

2023-06-29 15:52 UTC, maycomayco commented
> @maycomayco Comparing the stories with the XD, I don't see a `Story Hero Medium` story - were you considering that outside the scope? If so, can you create a separate ticket so we have an example for that, please?

The story for the Story Hero Medium component was defined on the examples page, now I moved that code to the templates page to keep it unified there.

2023-07-05 20:07 UTC, mlsamuelson approved these changes

2023-07-05 20:07 UTC, merged