docs(docs): relocated docs to their corresponding stories
ASU/asu-unity-stack pull request #1109
Opened 2023-07-13 00:11 UTC by davidornelas11

### Description
Relocate docs to their corresponding stories and Rename to readme to convey proper documentation to users

This ticket also has to do with [UDS-1421](https://asudev.jira.com/browse/UDS-1421?atlOrigin=eyJpIjoiMzdmZGM0MzY2ZjE0NGUwNzllYjgwZjY2MDVlMDk2ZDUiLCJwIjoiaiJ9) and this PR should be merged first or at least approved to be ready to merge before merging UDS-1421, as they touch some of the same files
### Links

- [JIRA ticket](https://asudev.jira.com/browse/UDS-1418?atlOrigin=eyJpIjoiYjE3Y2QzZjlhMTlhNGJmNmIyZDI0MGZhMTZjMDdiYzAiLCJwIjoiaiJ9)

### Checklist

- [x] Unity project successfully builds from root `yarn install` & `yarn build`
- [x] Commits do not contain multiple scopes
- [x] Add/updated examples
- [x] No new console errors
- [x] Accessibility checks

2023-07-14 18:41 UTC, scott-williams-az reviewed
**Readme files are often overlooked. Lets not hide them!**

Lets move these within the code as siblings of the story files (we will be more likely to update them)

- ~/stories/docs/blockquote/blockquote-basics.stories.mdx~
- `/stories/atoms/blockquote/blockquote-basics.stories.mdx`

I also don't see a need to nest the readmes in a `doc` folder (global-header might be the exception, but maybe not) 
~< Meta title="Atoms/Blockquotes and Testimonials/Docs/Blockquotes and Testimonials" />~
< Meta title="Atoms/Blockquotes and Testimonials/Blockquotes and Testimonials" />


Lets keep these on top, In storybook `.storybook/preview.js` file we will need to add ` ['Readme', '*']` to sort order
```storySort: {
      order: [
        'Design', ['Readme', '*'],
        [
          'Colors', ['Readme', '*'],
          'Typography', ['Readme', '*'],
          'Layout', ['Readme', '*'],
          'Icons', ['Readme', '*'],
          'Backgrounds', ['Readme', '*'],
          'Focus States', ['Readme', '*'],
        ],
        'Atoms', ['Readme', '*'],
        'Molecules', ['Readme', '*'],
        'Organisms', ['Readme', '*'],
        [
          'Global Header', ['Readme', '*'],
          [
            'Header top', ['Readme', '*'],
            'Header main', ['Readme', '*'],
            'Navbar options', ['Readme', '*'],
            'No navigation', ['Readme', '*'],
            'Additional considerations', ['Readme', '*'],
            'Mobile Breakpoint' ['Readme', '*'],
          ],
          'Content Sections', ['Readme', '*'],
          'Hero', ['Readme', '*'],
        ],
      ],
    }```

2023-07-19 00:33 UTC, davidornelas11 commented
I agree with Scott, that most doc files should be renamed readme to show users that this is important documentation that should be read first. With the exception being global header, as there are a few there.

2023-07-19 20:35 UTC, mlsamuelson requested changes

2023-07-19 20:35 UTC, mlsamuelson commented on packages/unity-bootstrap-theme/stories/docs/content-sections/content-image-overlap.stories.mdx
> +<Meta title="Organisms/Content Sections/Readme" />
This bit of documentation belongs under `Molecules/ Content Sections/Image Overlap/Readme` instead of here.

2023-07-19 20:38 UTC, mlsamuelson commented on packages/unity-bootstrap-theme/stories/docs/content-sections/content-image-overlap.stories.mdx
> +<Meta title="Organisms/Content Sections/Readme" />
Also, agreed with everything @scott-williams-az said.

2023-07-20 14:52 UTC, mlsamuelson approved these changes

2023-07-20 14:52 UTC, merged