Uds 1412
ASU/asu-unity-stack pull request #1116
Opened 2023-07-19 03:03 UTC by scott-williams-az

### Description

refreshing TabbedPanels with BS5
Removed `app-webdir-ui` logic from `components-core:TabbedPanels`

use `app-webdir-ui/examples/index.html?search-tabs=web_dir_faculty_staff&q=test` to test url parameters
- params should fill in search and select 2nd tab

### Links

- [@asu/components-core](https://unity.web.asu.edu/@asu/components-core/index.html?path=/story/uds-tabbedpanels--default)
- [@asu/app-webdir-ui](https://unity.web.asu.edu/@asu/app-webdir-ui/?path=/story/organisms-search-page-templates--search-page-example)
- [JIRA ticket](https://asudev.jira.com/browse/UDS-1412)
- [Unity Design Kit](https://xd.adobe.com/view/56f6cb78-9af5-4b12-b4ce-ef319f71113f-03a5/screen/674f1d96-f175-442a-8087-25cf3924e219/)

### Checklist

- [ ] Unity project successfully builds from root `yarn install` & `yarn build`
- [ ] Commits do not contain multiple scopes
- [ ] Add/updated examples
- [ ] No new console errors
- [ ] Accessibility checks

### Browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Images

2023-07-19 23:03 UTC, davidornelas11 reviewed
Aside from the error in proptypes on lint, this was tested in a webspark environment using ddev as well as a local ddev isearch environment and everything works!

2023-07-20 21:43 UTC, davidornelas11 submitted a review, later dismissed
LGTM

2023-07-24 15:44 UTC, mlsamuelson requested changes
Hm. Still experiencing issues:
* In Storybook: "Page Search Example" and "Faculty Rank Web Directory" stories, on a fresh load, the default tab detection/selection doesn't seem to be working and no content displays
* In Storybook: the buttons that navigate to different tabs' content work. Yay.
* In HTML example page (for search): default tab/content is selected and displayed.
* In HTML example page (for search): buttons that navigate to tab content don't work. (I tested in a second browser, in case it was caching. Same.)
* In HTML example page for web-directory: page fails to load. Looks like it's failing to get the token for the service call when the page loads - it seems it's hitting a local url instead of the `searchURL` value.

2023-07-26 16:17 UTC, scott-williams-az commented
This is ready for another look

2023-07-27 20:54 UTC, mlsamuelson approved these changes

2023-07-27 20:54 UTC, merged