fix(unity-bootstrap-theme): card horizontal fixed height and aspect r…
ASU/asu-unity-stack pull request #1129
Opened 2023-07-28 22:57 UTC by davidornelas11

…atio

### Description
Horizontal cards need to have a correct aspect ratio and fixed max-height. Card arrangements also needed to be added as a story to show horizontal cards in the card arrangements

### Links

- [Unity reference site](https://unity.web.asu.edu/@asu/unity-bootstrap-theme/index.html?path=/story/molecules-cards-examples--horizontal)
- [JIRA ticket](https://asudev.jira.com/browse/UDS-1297?atlOrigin=eyJpIjoiZTFjN2EzYjAzODBlNDdmMTg3NGVmOTI0YTU1NjZkMDciLCJwIjoiaiJ9)

### Checklist

- [x] Unity project successfully builds from root `yarn install` & `yarn build`
- [x] Commits do not contain multiple scopes
- [x] Add/updated examples
- [x] Add/updated READMEs/docs
- [x] No new console errors
- [x] Accessibility checks

### Browsers

- [x] Chrome
- [x] Safari
- [x] Firefox
- [x] Edge

2023-08-15 17:30 UTC, mlsamuelson requested changes
@davidornelas11 This is looking good. Like the new templating.  In mobile view with side-by-side horizontal cards, it looks like some work is needed. Could these switch to stacked in mobile?

![Screenshot 2023-08-15 at 10 29 00 AM](https://github.com/ASU/asu-unity-stack/assets/212131/46ae11da-27c8-4fc9-915c-807ba4eb7cfa)

2023-08-15 17:36 UTC, mlsamuelson commented
@davidornelas11 Looks like the mobile stacking happens with how these are implemented in WS2 (see https://dev-webspark-ci.ws.asu.edu/card-arrangement). So, would be nice if that showed in Storybook. Maybe not a requirement if it's a challenge.

2023-08-16 16:30 UTC, davidornelas11 commented
Not a challenge.; I can add that stacking

2023-08-17 02:06 UTC, davidornelas11 commented
> @davidornelas11 Looks like the mobile stacking happens with how these are implemented in WS2 (see https://dev-webspark-ci.ws.asu.edu/card-arrangement). So, would be nice if that showed in Storybook. Maybe not a requirement if it's a challenge.

So this most recent change i pushed up involves wrapping the horizontal cards in the card arrangement, as adding more templates using the templates control just adds another component outside the html-root wrapper, so it can not be altered from within the component. If my recent code is too messy, I suggest not having them stack since it is not a card arrangement

2023-08-21 18:41 UTC, scott-williams-az requested changes

2023-08-21 18:41 UTC, scott-williams-az commented on packages/unity-bootstrap-theme/stories/molecules/cards/cardVariations.js
> +export const horizontalCardsMap = (type = "", args) => {
change to  ({type = "", numCards=1})

2023-08-21 18:41 UTC, scott-williams-az commented on packages/unity-bootstrap-theme/stories/molecules/cards/cards.examples.stories.js
> +export default createComponent('Cards', 'Molecules', 'Examples', extraOptions);
Remove extraOptions and add it below to the one story that needs it

2023-08-21 18:41 UTC, scott-williams-az commented on packages/unity-bootstrap-theme/stories/molecules/cards/cards.examples.stories.js
> +cardImages.args  = {
Remove all instances of this code block
```
.args = {
  template: 1
};
cardTitles.parameters = {
  controls: { exclude: ["Columns"] },
};
```

2023-08-21 18:41 UTC, scott-williams-az commented on packages/unity-bootstrap-theme/stories/molecules/cards/cards.examples.stories.js
> +    {horizontalCard(null, args)}
change to `{horizontalCard({...args, type: null})}`

2023-08-21 18:41 UTC, scott-williams-az commented on packages/unity-bootstrap-theme/stories/molecules/cards/cards.examples.stories.js
> +    {horizontalCard("degree", args)}
change to `{horizontalCard({...args, type: "degree"})}`

2023-08-21 18:41 UTC, scott-williams-az commented on packages/unity-bootstrap-theme/stories/molecules/cards/cards.examples.stories.js
> +    {horizontalCard("event", args)}
change to `{horizontalCard({...args, type: "event"})}`

2023-08-21 18:41 UTC, scott-williams-az commented on packages/unity-bootstrap-theme/stories/molecules/cards/cards.examples.stories.js
> +    {horizontalCard("story", args)}
change to `{horizontalCard({...args, type:"story"})}`

2023-08-21 18:41 UTC, scott-williams-az commented on packages/unity-bootstrap-theme/stories/molecules/cards/cards.examples.stories.js
add the extraOptions here
```
horizontal.argTypes = {
  numCards: {
    name: "Columns",
    options: [1, 2, 3, 4],
    defaultValue: 1,
    control: {
      type: "radio",
    },
  }
}
```

2023-09-06 22:41 UTC, mlsamuelson approved these changes

2023-09-06 22:42 UTC, mlsamuelson commented
I've approved. Can't be merged until @scott-williams-az also approves since he had requested changes. From what I see, those changes were made.

2023-09-14 17:20 UTC, scott-williams-az approved these changes

2023-09-14 17:20 UTC, merged