feat: added shared global variable func
ASU/asu-unity-stack pull request #1160
Opened 2023-09-07 23:30 UTC by davidornelas11

### Description
Each component needs to have a global variable added with info about that component for easy tracking using tag manager. 

### Links

- [JIRA ticket](https://asudev.jira.com/browse/UDS-1460?atlOrigin=eyJpIjoiNWRjOTU3MTg5MTdkNDgzODk3MGU5Nzc1ZGU0OTFmY2IiLCJwIjoiaiJ9)

### Checklist

- [x] Unity project successfully builds from root `yarn install` & `yarn build`
- [x] Commits do not contain multiple scopes
- [x] Add/updated examples
- [x] Add/updated READMEs/docs
- [x] No new console errors
- [x] Accessibility checks

### Browsers

- [x] Chrome
- [x] Safari
- [x] Firefox
- [x] Edge

### Images

2023-09-08 17:36 UTC, scott-williams-az commented on shared/functions/componentDatalayer.js
> +  if (!componentName || !package || !component || !configuration) {
Remove `configuration` check req another way

with the default `configuration = {}`, `!configuration` will always be `false` unless the user passes in a value like false (which wouldn't make sense)

2023-09-08 17:36 UTC, scott-williams-az commented on shared/functions/componentDatalayer.js
> +  window.udsComponent = window.udsComponent || {};
I'd like to start using this pattern more, what do you think of nesting further so we can use more things nested under one scope. `window.uds.dataLayer.component` and `window.uds.awesomeObjectOrFn`

2023-09-08 17:36 UTC, scott-williams-az commented on shared/functions/componentDatalayer.js
> +      type: type,
I believe default empty string for `type` is OK, just checking.

2023-09-12 01:22 UTC, davidornelas11 commented on shared/functions/componentDatalayer.js
> +  window.udsComponent = window.udsComponent || {};
The only caveat of using this nested pattern is that the dataLayer must stay in the direct descendent window object for tag manager, i believe. But other than that I'm all for nesting the rest.

2023-10-02 21:09 UTC, mlsamuelson requested changes
For `components-core` I’m thinking we don’t want to capture a global variable for those components  that would be used inside another component multiple times - like buttons, etc.  The spirit of what we want to track is "app-level" configs.  So global variable settings for button, card and testimonial components.... not the desired outcome.  For components core I think you could make a case for tracking the Pagination and TabbedPanels components... since there's likely to only be one on a page, but even then, maybe they're not necessary. ... `components-core` exists for other higher level components to use, so maybe we should not track anything from it.

2023-10-02 21:09 UTC, mlsamuelson commented on packages/app-rfi/src/components/AsuRfi/index.js
> +          studentType,
On the RFI component, tracking all configurations except for the `dataSource*` and `submissionUrl` props would be helpful. If it makes it easier, we could just rack the full set of props.

2023-10-02 21:09 UTC, mlsamuelson commented on packages/component-footer/src/footer.js
> +        component: "NA",
We should always have a component name.

2023-10-02 21:09 UTC, mlsamuelson commented on packages/component-header/src/header.js
> +        component: "NA",
We should have a component name.

2023-10-02 21:09 UTC, mlsamuelson commented on packages/component-header/src/header.js
> +        component: "NA",
Could we include a few more that are boolean true if present:
`navTree`
`parentOrg`
`buttons`
`mobileNavTree`

2023-10-02 21:09 UTC, mlsamuelson commented on packages/component-news/src/components/CardGridNews/index.js
> +          ...props,
Between `CardCarouselNews` and `CardGridNews` components the props are handled inconsistently - one uses spreading, the other doesn't. Let's be consistent.

2023-10-02 21:09 UTC, mlsamuelson commented on packages/component-news/src/components/CardListlNews/index.js
> +        configuration: {},
Missing `cardButton` and `props` to match `CardGridNews` and `CardCarouselNews` implementations.

2023-10-02 21:09 UTC, mlsamuelson commented on shared/functions/componentDatalayer.js
> +  window.udsComponent = window.udsComponent || {};
Let's keep the `window.udsComponent` for this usage, since it needs to be a direct descendent for GTM to parse. But for all other UDS globals in the future, I agree with @scott-williams-az about nesting under `.uds` like so `window.uds.coolnessGoesHere`.

2023-10-30 17:26 UTC, mlsamuelson submitted a review, later dismissed

2023-10-30 17:26 UTC, mlsamuelson commented on shared/functions/componentDatalayer.js
Rename `shared/functions` to `utilities/datalayer`.

2023-11-16 23:05 UTC, mlsamuelson commented on shared/functions/componentDatalayer.js
@davidornelas11 Bumping this as a reminder. Just needs the path renamed.

2024-01-11 20:20 UTC, mlsamuelson approved these changes

2024-01-11 20:20 UTC, merged