Percy visual regression testing
ASU/asu-unity-stack pull request #1237
Opened 2024-02-07 08:56 UTC by davidornelas11

### Description
Added percy visual regression testing with story config

TESTING STEPS:
If running tests locally and only wanting to check a dry run, you must set `PERCY_PARALLEL_NONCE=<random alphanumeric string>` and add the --dry-run flag to the percy-testing.js script. If you do not have the token set in your local environment, you can safely run this without the dry run flag as it will not upload but all other steps will run.

### Links

- [Unity reference site](https://unity.web.asu.edu/)
- [JIRA ticket](https://asudev.jira.com/browse/UDS-1210?atlOrigin=eyJpIjoiMTQ1NTZmMDYyY2RiNDY2ZmFhYTI3OTc5NDI0MjAxYjMiLCJwIjoiaiJ9)

### Checklist

- [x] Unity project successfully builds from root `yarn install` & `yarn build`
- [x] Commits do not contain multiple scopes
- [x] Add/updated examples
- [x] Add/updated READMEs/docs
- [x] No new console errors
- [x] Accessibility checks

### Browsers

- [x] Chrome
- [x] Safari
- [ ] Firefox
- [x] Edge

### Images

2024-03-01 21:59 UTC, mlsamuelson requested changes

2024-03-01 21:59 UTC, mlsamuelson commented on README.md
> +  - [Visual Regression Testing](#visual-regression-testing)
@davidornelas11 This PR is almost good to go except let's move the Visual Regression section to right before the "Running end-to-end testing" section. That would mean moving line 8 to right above line 25 (or 24 when line 8 is removed 😛 ) and then moving the related block of content to the same position in the body of the document.

2024-03-04 17:47 UTC, mlsamuelson requested changes

2024-03-04 17:47 UTC, mlsamuelson commented on README.md
> +1. Install the package using yarn or npm:
Regression in numbering.

2024-03-04 17:58 UTC, mlsamuelson approved these changes

2024-03-04 18:56 UTC, iodeslykos approved these changes
Approving `Jenkinsfile`.

2024-03-04 19:39 UTC, merged