fix(unity-bootstrap-theme): fixed overlapping h1 when text wraps
ASU/asu-unity-stack pull request #1271
Opened 2024-04-24 20:40 UTC by davidornelas11

### Description
fixed overlapping h1 when text wraps

### Links

- [Unity reference site](https://unity.web.asu.edu/@asu/unity-bootstrap-theme/index.html?path=/story/molecules-heroes-examples--hero-small-one-button)
- [JIRA ticket](https://asudev.jira.com/browse/UDS-1656?atlOrigin=eyJpIjoiZDliMDI2YWMwOTEzNGYxYWEzYzdhNGZmMjcyNmViMTgiLCJwIjoiaiJ9)

### FOR APPROVERS

- [Percy build approval](https://percy.io/5eae92d9/-all-UDS-packages)

### Checklist

- [ ] Unity project successfully builds from root `yarn install` & `yarn build`
- [ ] Commits do not contain multiple scopes
- [ ] Add/updated examples
- [ ] Add/updated READMEs/docs
- [ ] No new console errors
- [ ] Accessibility checks

### Browsers

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Images

![Problem example](https://github.com/ASU/asu-unity-stack/assets/21250684/aaa71b14-ab23-4621-b4b1-c1b19806dcee)

2024-04-26 21:42 UTC, mlsamuelson requested changes
Looks like when the h1 wraps there's a 1px gap with the new spacing:
<img width="1086" alt="Screenshot 2024-04-26 at 2 40 25 PM" src="https://github.com/ASU/asu-unity-stack/assets/212131/a29d9843-b00a-4aef-a4ae-8a366a3fc139">

Previously no gap:
<img width="1201" alt="Screenshot 2024-04-26 at 2 40 37 PM" src="https://github.com/ASU/asu-unity-stack/assets/212131/84bfa6aa-d54f-459e-95cb-772af228c396">

The XD doesn't show wrap for desktop, but for mobile there's no gap between lines so we need to make sure we don't have a gap here: https://xd.adobe.com/view/56f6cb78-9af5-4b12-b4ce-ef319f71113f-03a5/screen/2507e745-04a5-495a-a49a-f8f6bd82c155/specs/

2024-04-26 22:29 UTC, scott-williams-az commented
@davidornelas11 piggy back from Michaels comment.

I played with the numbers and this seems to work no matter what font-size
`line-height: calc(113% - 1px);`
(You can ignore me, if you already have a solution that covers things)

2024-04-27 00:18 UTC, davidornelas11 commented
> @davidornelas11 piggy back from Michaels comment.
> 
> I played with the numbers and this seems to work no matter what font-size `line-height: calc(113% - 1px);` (You can ignore me, if you already have a solution that covers things)

That leaves the same space if it wraps on mobile past 2 lines. I think changing the padding on the span for these h1's that have these styles will work
![Screen Shot 2024-04-26 at 5 17 40 PM](https://github.com/ASU/asu-unity-stack/assets/21250684/a331fed8-380e-49eb-89c4-5d0f9e63bc32)

2024-05-03 22:59 UTC, mlsamuelson requested changes
So close, but I noticed the fix resulted in one pixel of clipping... See issue and fix in screenshots.
<img width="1208" alt="Screenshot 2024-05-03 at 3 57 02 PM" src="https://github.com/ASU/asu-unity-stack/assets/212131/823733aa-0bdd-4c4c-bbe1-905ab4caa98a">
<img width="1193" alt="Screenshot 2024-05-03 at 3 57 28 PM" src="https://github.com/ASU/asu-unity-stack/assets/212131/e3513978-09b4-455d-aac6-0003d80991fb">

2024-05-03 23:45 UTC, mlsamuelson approved these changes

2024-05-03 23:45 UTC, merged