fix(component-footer): corrected footer links
ASU/asu-unity-stack pull request #1286
Opened 2024-05-25 00:16 UTC by davidornelas11

### Description
corrected footer links

### Links

- [Unity reference site](https://unity.web.asu.edu/)
- [JIRA ticket](https://asudev.jira.com/browse/UDS-1698?atlOrigin=eyJpIjoiMGZjMjljYWZjNTI1NDA3YWFlODY0OGJmMWViY2VlODYiLCJwIjoiaiJ9)
- [Unity Design Kit](https://xd.adobe.com/view/6c0089d7-e4f5-49cf-9c0c-677e90603cf4-3953/)

### FOR APPROVERS

- [Percy build approval](https://percy.io/5eae92d9/-all-UDS-packages)

### Checklist

- [x] Unity project successfully builds from root `yarn install` & `yarn build`
- [x] Commits do not contain multiple scopes
- [x] Add/updated examples
- [x] Add/updated READMEs/docs
- [x] No new console errors
- [x] Accessibility checks

### Browsers

- [x] Chrome
- [x] Safari
- [x] Firefox
- [x] Edge

### Images

2024-06-10 20:12 UTC, mlsamuelson requested changes
This misses some of the commentary in the ticket description - to avoid redirects, the Directory links should just go straight to `https://search.asu.edu/?search-tabs=web_dir_faculty_staff` instead of `https://isearch.asu.edu/asu-people`

2024-06-14 23:16 UTC, scott-williams-az submitted a review, later dismissed

2024-06-14 23:16 UTC, scott-williams-az commented on packages/component-footer/src/core/constants/index.js
> +export { FOOTER_URLS, LEGAL_URLS };
export * from "./constants";

2024-06-14 23:16 UTC, scott-williams-az commented on packages/unity-bootstrap-theme/stories/organisms/global-footer/global-footer.templates.js
> -                  href="https://www.asu.edu/asujobs"
can we use those constants for all the hrefs?
`href={FOOTER_URLS.JOBS}`

2024-06-14 23:21 UTC, scott-williams-az commented
It looks like you resolved Michaels request. Approved with 2 requested changes 
https://github.com/ASU/asu-unity-stack/pull/1286#discussion_r1640437370
https://github.com/ASU/asu-unity-stack/pull/1286#discussion_r1640438837

2024-06-14 23:25 UTC, scott-williams-az commented on packages/component-footer/src/core/constants/index.js
> +export { FOOTER_URLS, LEGAL_URLS };
Actually is there a better file name/ path? this seems redundant
- `/core/constants`
  - `/core/constants/constants.js`
  - `/core/constants/index.js`

2024-06-17 22:55 UTC, davidornelas11 commented on packages/unity-bootstrap-theme/stories/organisms/global-footer/global-footer.templates.js
> -                  href="https://www.asu.edu/asujobs"
I'm a bit conflicted about this. Should I move the footer urls from components footer into the shared and keep it there and refactor any other package that uses these? Or just have 2 copies in each package?

2024-06-21 17:17 UTC, davidornelas11 commented on packages/unity-bootstrap-theme/stories/organisms/global-footer/global-footer.templates.js
> -                  href="https://www.asu.edu/asujobs"
I'm going to make a different ticket for this since it's non blocking

2024-06-26 17:39 UTC, mlsamuelson approved these changes

2024-06-26 17:40 UTC, merged