Uds 1683
ASU/asu-unity-stack pull request #1326
Opened 2024-07-24 03:47 UTC by scott-williams-az

### Description

This ticket has 3 items, This PR address item 1 `The doc-subtitle role is exposed as a heading with no level`
- The doc-subtitle role is meant for document, it is not meant for web

hgroup was being deprecated, however it may have made a come back as I still see relevant documentation:
- https://html.spec.whatwg.org/multipage/sections.html#the-hgroup-element
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/hgroup
There is another option to use header which does have an example of text before the h1
- https://html.spec.whatwg.org/multipage/sections.html#the-header-element

### Links

- [JIRA ticket](https://asudev.jira.com/browse/UDS-1638) 
- [Unity reference site](https://asu.github.io/asu-unity-stack/)
- [Unity Design Kit](https://shared-assets.adobe.com/link/fb14b288-bf63-47e0-5d30-384de5560455)

### FOR APPROVERS

- [Percy build approval](https://percy.io/5eae92d9/-all-UDS-packages)

2024-07-29 20:04 UTC, mlsamuelson requested changes
Looks good. Cleanly implemented. A commit for each package. Thx!

Because there’s a markup change in the `unity-bootstrap-theme` that will require consumers to update their markup, what do you think about having a “breaking change” commit so it gets a breaking (major) release?  Historically that’s how we’ve handled it in the BS theme when markup changes. The React component doesn't need it because it handles its own markup.

2024-07-31 17:07 UTC, scott-williams-az commented
I thought about making it a breaking change, but because the code is still backwards compatible So that is why I did not, but I can make that commit.

2024-07-31 17:18 UTC, mlsamuelson commented
All good if it's backwards compatible. :) Thanks, @scott-williams-az .

2024-07-31 17:19 UTC, mlsamuelson approved these changes

2024-07-31 17:31 UTC, merged