Uds 1685: Add keyboard navigation to header
ASU/asu-unity-stack pull request #1332
Opened 2024-07-29 22:00 UTC by davidornelas11

### Description
Added full keyboard navigation with header dropdown menus.

For testing:
1. Dropdown menus should be navigable with the keyboard arrows as well as tab
2. When inside a dropdown menu, the esc key should close the menu and put the focus at the parent link
3. Voiceover should recognize if the menu is expanded or not

### Links

- [JIRA ticket](https://asudev.jira.com/browse/UDS-1685)

### FOR APPROVERS

- [Percy build approval](https://percy.io/5eae92d9/-all-UDS-packages)

2024-07-31 14:38 UTC, mlsamuelson requested changes
Couple questions, @davidornelas11. 

Because it's used for more than focusing the next link, what do you think about renaming `focusOnNextLink()` to `handleLinkFocus()` or something similar, to better reflect what that function does?

Do we need to implement similar updates for the Bootstrap version of the header?

2024-07-31 22:50 UTC, davidornelas11 commented
> Couple questions, @davidornelas11.
> 
> Because it's used for more than focusing the next link, what do you think about renaming `focusOnNextLink()` to `handleLinkFocus()` or something similar, to better reflect what that function does?
> 
> Do we need to implement similar updates for the Bootstrap version of the header?

i agree on renaming the function. As far as the unity-bootstrap-theme, we would need to include the custom js file in the storybook with some instructions but it would just be for people who implement that instead of the react header.

2024-07-31 23:02 UTC, mlsamuelson requested changes
Yes, so let's update the function name.

And thanks for the reminder that we're not currently shipping the header JS. It's not functionally equivalent in that regard at this time, so when we implement that, we can address sharing "current" JS. No work needed there, currently.

2024-08-05 20:41 UTC, mlsamuelson approved these changes

2024-08-05 20:41 UTC, merged