UDS-1775: fix(unity-bootstrap-theme): switch anchor to button on accordions header and added styles
ASU/asu-unity-stack pull request #1335
Opened 2024-07-31 14:38 UTC by juanmitriatti

fix(unity-bootstrap-theme): switch anchor to button on accordions header and added styles

UDS-1775

### Description

#### Solution
Switch over to use buttons instead of anchor tags ad that solves it for us without the need for custom javascript.

### Links

- [JIRA ticket](https://asudev.jira.com/browse/UDS-1775)
- [Unity reference site](https://asu.github.io/asu-unity-stack/)
- [Unity Design Kit](https://shared-assets.adobe.com/link/fb14b288-bf63-47e0-5d30-384de5560455)

### FOR APPROVERS

- [Percy build approval](https://percy.io/5eae92d9/-all-UDS-packages)

2024-07-31 22:50 UTC, mlsamuelson requested changes
2 issues:

1. In testing this, I'm not seeing the focus state for the accordion header/button, and that's a regression. See the "states" tab for how that should be styeld: https://zeroheight.com/9f0b32a56/p/39a26f-accordion 

2. There is a React version of the accordion in `components-core` and it will need to get updated as well. The commit to add that update should use the `components-core` scope so it triggers a release for that package when this is merged. If you have questions about this version of the accordion, please reach out to Dave or Scott. https://asu.github.io/asu-unity-stack/@asu/components-core/index.html?path=/story/uds-accordion--default

2024-08-01 18:24 UTC, juanmitriatti commented
> 2 issues:
> 
> 1. In testing this, I'm not seeing the focus state for the accordion header/button, and that's a regression. See the "states" tab for how that should be styeld: https://zeroheight.com/9f0b32a56/p/39a26f-accordion
> 2. There is a React version of the accordion in `components-core` and it will need to get updated as well. The commit to add that update should use the `components-core` scope so it triggers a release for that package when this is merged. If you have questions about this version of the accordion, please reach out to Dave or Scott. https://asu.github.io/asu-unity-stack/@asu/components-core/index.html?path=/story/uds-accordion--default

Hi @mlsamuelson 
Regarding this first concern, please check these images : 

**Image 1** : This is what I locally see using the new approach "_w/ button: focus enabled in h4 or button_"
![image](https://github.com/user-attachments/assets/1491ec43-c477-4af4-80e7-71facd600d19)
----------------------------------

**Image 2** : This is what I see using the previous approach "_w/ anchor, focus enabled in h4 tag_"
![image](https://github.com/user-attachments/assets/adb330dc-d751-4d70-b63b-4b834c860d8e)

Would you please explain me the error that I'm introducing here? Thanks!

2024-08-01 20:50 UTC, mlsamuelson commented
Thanks for the question, @juanmitriatti . As we discovered when we Zoomed about this issue, it turns out that the missing focus state is a problem in the current `unity-bootstrap-theme` and `components-core` version of the accordions. It makes sense to fix it here. 

Please also check the Open and Close toggle on Accordions in multiple browsers. In my testing, the accordions only open in Chrome, but in Firefox they both open and close. The Firefox behavior is correct.

2024-08-05 20:30 UTC, mlsamuelson requested changes
This PR updates both `unity-bootstrap-theme` and `components-core` but it only has commits for the `unity-boostrap-theme` scope. Can you do a commit with `fix(components-core)` as the scope so that component will get an updated release, please? You can do a small edit to the README.md in that component for that commit.

2024-08-05 20:33 UTC, mlsamuelson commented
Once we have a commit for the `components-core` scope, this should be good.

2024-08-07 17:07 UTC, juanmitriatti commented
Hi @mlsamuelson 
This is done. Please review the last commit.
Thanks!

2024-08-07 17:50 UTC, mlsamuelson approved these changes

2024-08-07 17:50 UTC, merged