Component consolidation
ASU/asu-unity-stack pull request #1346
Opened 2024-08-26 23:23 UTC by davidornelas11

### Description
This is the main feature branch for the component consolidation effort

### Links

- [JIRA ticket](https://asudev.jira.com/browse/UDS-1571)

### FOR APPROVERS

- [Percy build approval](https://percy.io/5eae92d9/-all-UDS-packages)

2024-10-14 22:25 UTC, mlsamuelson requested changes

2024-10-14 22:25 UTC, mlsamuelson commented on packages/app-degree-pages/public/assets/img/demo-phot-4.jpeg
Please use a different image. We don't want to include an image in our codebase that has a QR code that we don't know to where it's pointing.

2024-10-14 22:48 UTC, davidornelas11 commented on packages/app-degree-pages/public/assets/img/demo-phot-4.jpeg
Removed

2025-01-14 22:50 UTC, mlsamuelson requested changes
Issues to resolve before merge:
* [x] unspalsh images need to be replaced in Image, Heroes, Card and wherever they occur.
* [ ] carousel based stories need to force React version. When Bootstrap version displays, they are not interactive.
* [ ] Modal and Tabbed Panels stories throw error on Docs page.
* [ ] Static site footer image
* [ ] table fixed story needs to force React version. Bootstrap version is not interactive. Also errors on Docs page.

2025-01-15 17:42 UTC, mlsamuelson commented
Also need to ensure that component-header-footer works in WS2 before we merge this. cc @davidornelas11

2025-01-15 17:46 UTC, mlsamuelson commented
UDS-1912 to update use of unity-react-core internally is still pending, too. cc @scott-williams-az

2025-01-28 22:27 UTC, mlsamuelson commented
## Root README.md
* https://github.com/ASU/asu-unity-stack/tree/component-consolidation?tab=readme-ov-file#packages-in-this-repository Packages list needs update. Note what's deprecated (move to section below). Add new.

2025-02-06 20:59 UTC, mlsamuelson approved these changes

2025-02-06 21:02 UTC, mlsamuelson commented
Individual PRs reviewed as the went into this feature branch. Also reviewed high level on this branch, and tested S3 static reference site built from this branch.

2025-02-06 22:24 UTC, iodeslykos approved these changes
Approving `Jenkinsfile` and README, because I read it.

2025-02-06 22:54 UTC, merged