feat(component-carousel): added aria-hidden for unvisible cards
ASU/asu-unity-stack pull request #1348
Opened 2024-08-28 20:42 UTC by juanmitriatti

UDS-1805

### Description

#### Solution 
Added aria-hidden and tabindex for visible and unvisible cards

### Links

- [JIRA ticket](https://asudev.jira.com/browse/UDS-1805)
- [Unity reference site](https://asu.github.io/asu-unity-stack/)
- [Unity Design Kit](https://shared-assets.adobe.com/link/fb14b288-bf63-47e0-5d30-384de5560455)

### FOR APPROVERS

- [Percy build approval](https://percy.io/5eae92d9/-all-UDS-packages)

2024-08-29 16:50 UTC, davidornelas11 approved these changes
Looks good!

2024-09-03 23:27 UTC, davidornelas11 requested changes
On further testing i realized that the buttons are still reachable via tabindex and voiceover. The parent element with a tabindex of -1 and aria-hidden true does not affect children that are inherently focusable.

Using the `inert` attribute seems to work for all children elements. It is available in all browsers as well
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inert

2024-09-04 23:45 UTC, mlsamuelson approved these changes

2024-09-05 01:15 UTC, davidornelas11 approved these changes

2024-09-05 01:17 UTC, merged