Cc vitest sbname plop
ASU/asu-unity-stack pull request #1370
Opened 2024-09-27 19:06 UTC by scott-williams-az

### Description
- autofix and rename stories (removing UDS, we can add parent folders again if we have a need to separate in the future)
- switch to vitest (Most tests pass, 4 tests do not and I think the tests need to be rewritten. Search the code for .skip to find them)
- prepare for new ts components `yarn create`
  - creates:
    - /src/components/NewComponent/NewComponent.tsx
    - /examples/new-component.html
    - /src/components/NewComponent/NewComponent.stories.tsx
    - /src/components/NewComponent/NewComponent.test.tsx
    - /src/components/NewComponent/index.js
  - adds (import/export statements):
    - /src/components/index.js
    - /src/core/utils/index.js
- added package script `yarn dev` starts storybook and vitest UI for auto feedback on testing

### Links

- [JIRA ticket](https://asudev.jira.com/browse/UDS-0000)
- [Unity reference site](https://asu.github.io/asu-unity-stack/)
- [Unity Design Kit](https://shared-assets.adobe.com/link/fb14b288-bf63-47e0-5d30-384de5560455)

### FOR APPROVERS

- [Percy build approval](https://percy.io/5eae92d9/-all-UDS-packages)

2024-09-28 00:59 UTC, davidornelas11 requested changes
A few changes as well as possibly extracting the ts switchover into it's own branch and ticket

2024-09-28 00:59 UTC, davidornelas11 commented on packages/unity-react-core/examples/index.html
> +<!DOCTYPE html>
Was this file made by mistake? Doesn't seem to have anything in it

2024-09-28 00:59 UTC, davidornelas11 commented on packages/unity-react-core/package.json
> +    "test": "vitest",
This is not blocking since watch false is automatically added in CI, but we should add `--watch=false` to the `test` script since we already have the testui script when we want to run it in watch mode with the ui when developing locally.

2024-09-28 00:59 UTC, davidornelas11 commented on packages/unity-react-core/tsconfig.json
> +    "rootDir": "src",
There's a TS error here so we should either make `.` as the rootDir or remove `"**/*.ts",
    "**/*.tsx",
    "./vitest.setup.ts",` and add them to a "files" field.
Actually after further testing, there are errors all over the code base in my IDE since its reading the tsconfig file in unity-react-core and applying that everywhere. we might want to put this into it's own ticket and do it all at once unless we're all ok with the errors. It does make development a bit harder though

2024-10-02 22:57 UTC, scott-williams-az commented on packages/unity-react-core/examples/index.html
> +<!DOCTYPE html>
I created this page so `http://localhost:5500/packages/unity-react-core/examples/` would have an index page with the navigation

2024-10-03 18:56 UTC, scott-williams-az commented
I think the alias "@shared" is the thing that is messing things up. so I might need to remove that for now

2024-10-03 19:49 UTC, scott-williams-az commented
I just removed the alias for now

2024-10-08 21:11 UTC, merged