fix(component-header): fix dataLayer firing on parent dropdown click
ASU/asu-unity-stack pull request #1372
Opened 2024-10-01 22:14 UTC by davidornelas11

### Description
fix dataLayer firing on parent dropdown click

### Links

### FOR APPROVERS

- [Percy build approval](https://percy.io/5eae92d9/-all-UDS-packages)

2024-10-01 22:27 UTC, chill5-0 submitted a review, later dismissed
Approved

JIRA: https://asudev.jira.com/browse/WS2-2353

2024-10-01 23:26 UTC, mlsamuelson requested changes
Data Layer is firing for the dropdowns, top level menu items, secondary menu items.

But we have mostly empty events firing for...
* Links in the gray universal nav area (search input and toggle controls are okay for that, though.)
* ASU Logo
* Partner Logo
* Site title (subdomain)
* Parent Unit
* CTAs in the top level of the header
* Buttons in the dropdowns

2024-10-02 16:16 UTC, mlsamuelson commented
For reference https://xd.adobe.com/view/907fadbe-e90a-40a8-a0b7-2396bd9450dd-c52c/

2024-10-02 20:40 UTC, chill5-0 commented on packages/component-header/src/components/HeaderMain/Logo/index.js
@davidornelas11 I think this should be onClick, not onFocus?

2024-10-02 20:42 UTC, davidornelas11 commented on packages/component-header/src/components/HeaderMain/Logo/index.js
Good catch. Fixed

2024-10-02 20:55 UTC, chill5-0 approved these changes, later dismissed
Approved

2024-10-02 21:29 UTC, mlsamuelson commented on packages/component-header/src/components/HeaderMain/Title/index.js
> +          onFocus={() =>
Should this one still be onFocus() ?

2024-10-03 16:46 UTC, mlsamuelson approved these changes

2024-10-03 16:49 UTC, mlsamuelson requested changes
3 build errors to fix:

<img width="1253" alt="Screenshot 2024-10-03 at 9 49 08 AM" src="https://github.com/user-attachments/assets/defe44d2-59f2-41e4-a75b-dce9a5c8fb19">

2024-10-03 17:01 UTC, mlsamuelson commented on packages/component-header/src/components/HeaderMain/NavbarContainer/DropdownItem/index.js
> +      onClick={() => trackGAEvent({ text: link.text, component: dropdownName })}
onClick on lines 54 and 56 - triggers no duplicate props linting error. Need just one. Assuming it's 56.

2024-10-03 17:03 UTC, mlsamuelson commented on packages/component-header/types/main.d.ts
> +  onClick?: () => void;
Duplicates previous line.

2024-10-03 20:13 UTC, mlsamuelson approved these changes
Verified.

2024-10-03 20:13 UTC, merged

2024-10-03 21:35 UTC, mlsamuelson commented
Associated ticket for this is WS2-2366