lists
ASU/asu-unity-stack pull request #1381
Opened 2024-10-16 18:06 UTC by scott-williams-az

2024-11-21 23:20 UTC, mlsamuelson requested changes
Example not rendering, probably due to needing to use React 18.

Also, when list html rendes in storybook, when controls are set to default colors, the word `null` renders in the list's class attribute:
![Screenshot 2024-11-21 at 4 19 41 PM](https://github.com/user-attachments/assets/6a1a895c-1e2f-4e19-b88b-17684936ada8)

2024-11-21 23:20 UTC, mlsamuelson commented on packages/unity-react-core/examples/list.html
> +  <script src="https://unpkg.com/react-dom@17/umd/react-dom.production.min.js" crossorigin></script>
Need to use React 18

2024-11-22 22:56 UTC, scott-williams-az commented on packages/unity-react-core/examples/list.html
> +  <script src="https://unpkg.com/react-dom@17/umd/react-dom.production.min.js" crossorigin></script>
done

2024-11-22 23:12 UTC, mlsamuelson commented
Screenshot and issue reported with the nulls was incorrect. Must have been looking at the wrong browser tab. Apologies.

2024-12-03 19:17 UTC, mlsamuelson approved these changes

2024-12-03 19:18 UTC, merged

2024-12-03 19:21 UTC, mlsamuelson commented
Didn't find a Jira ticket specifically for this story, but it's not merged and part of the larger effort, so I'm not going to bother creating a ticket at this point.