Uds 1667
ASU/asu-unity-stack pull request #1391
Opened 2024-10-29 22:42 UTC by scott-williams-az

### Description

### Links

- [JIRA ticket](https://asudev.jira.com/browse/UDS-1667)
- [Unity reference site](https://asu.github.io/asu-unity-stack/)

2024-10-30 00:37 UTC, davidornelas11 commented
![Screenshot 2024-10-29 at 5 00 46 PM](https://github.com/user-attachments/assets/5de7f54a-3c70-4450-b797-66ed1d2a1e93)
Static site package looks good. There's a weird style clash with z-index but it's unrelated.

2024-10-31 22:37 UTC, mlsamuelson reviewed
Linting errors.

<img width="1675" alt="Screenshot 2024-10-31 at 3 36 13 PM" src="https://github.com/user-attachments/assets/496bccc7-589d-487a-842e-3dc32332b198">

2024-10-31 22:51 UTC, mlsamuelson commented on packages/static-site/README.md
> +- Development server uses a custom host, which needs to be added to your machines host file `127.0.0.1 localhost.unity.web.asu.edu`
Should be `127.0.0.1 localhost.asu.edu` to match what code expects and instructions on line 12.

2024-10-31 23:19 UTC, mlsamuelson requested changes
Header scroll behavior missing (shrinking on scroll). Not a deal-breaker for initial rollout, but maybe an easy fix?

Z-index, as noted by @davidornelas11 scolling over the header.

As noted, in conversation, to be solved: linking directly to routes, or refreshing the page after having browsed to a route should not return a broken/missing page.

2024-11-01 15:14 UTC, mlsamuelson commented
Also, when I built and ran locally, the Storybook references weren't in place. Is that expected in this case, or indicative of work to be done?

2024-11-07 16:23 UTC, scott-williams-az commented
The footer image path is defaulting to root. Haven't figure this out yet, I am hoping it is a simple fix in vite.config
<img width="1422" alt="image" src="https://github.com/user-attachments/assets/816eb3b7-c298-44c5-b31a-e62864b8714b">

2024-11-21 15:42 UTC, scott-williams-az commented
replaced PR with https://github.com/ASU/asu-unity-stack/pull/1401

2024-11-21 15:42 UTC, closed without merging