Uds 1876 - Add sidebar
ASU/asu-unity-stack pull request #1394
Opened 2024-10-30 19:58 UTC by davidornelas11

### Description
Add sidebar to unity react core

### Links

- [JIRA ticket](https://asudev.jira.com/browse/UDS-1876?atlOrigin=eyJpIjoiZTBlZjlhMTgyMmYzNDdiYWE0YzZiNGNiMzIyNmMzY2EiLCJwIjoiaiJ9)

2024-10-30 19:59 UTC, davidornelas11 commented
@scott-williams-az I added the isActive boolean to the props but wasn't sure if we should take care of that programatically by checking the window.location and seeing what link matches the window location. Thoughts?
CC: @mlsamuelson

2024-11-13 18:52 UTC, davidornelas11 commented
Waiting on the useExternal function in https://github.com/ASU/asu-unity-stack/pull/1397 to merge into the consolidation branch before updating this as this will depend on that

2024-11-13 19:10 UTC, mlsamuelson commented
@davidornelas11 How about, first a check for an `isActive` item and if not found, then do a `window.location` check to set active (being defensive against there  being no `window` potentially (due to possible NodeJS or SSR usage in the future)?

2024-11-13 19:21 UTC, mlsamuelson commented on packages/unity-react-core/examples/sidebar-menu.html
> +  <script src="https://unpkg.com/react-dom@17/umd/react-dom.production.min.js" crossorigin></script>
Probably need to use React 18 here...

2024-11-13 19:24 UTC, mlsamuelson commented on packages/unity-react-core/examples/sidebar-menu.html
> +  <script src="https://unpkg.com/react-dom@17/umd/react-dom.production.min.js" crossorigin></script>
This was addressed in the templating in https://github.com/ASU/asu-unity-stack/pull/1396

2024-11-13 19:25 UTC, davidornelas11 commented on packages/unity-react-core/examples/sidebar-menu.html
> +  <script src="https://unpkg.com/react-dom@17/umd/react-dom.production.min.js" crossorigin></script>
Good catch. I used the plop helper before the react 18 upgrade last week

2024-11-13 19:29 UTC, mlsamuelson commented on packages/unity-react-core/src/components/SidebarMenu/SidebarMenu.test.tsx
> +      href: "#",
Because we get dinged on hrefs with the path `#` when accessibility testing happens, can we instead standardize on `https://example.com`?

2024-11-13 19:35 UTC, mlsamuelson requested changes

2024-11-13 19:35 UTC, mlsamuelson commented on packages/unity-react-core/src/core/utils/index.js
> +import { SidebarMenu } from "../../components/SidebarMenu/SidebarMenu.tsx";
Can this import please be put at the top of the file in alpha order with the other imports?

2024-11-13 19:35 UTC, mlsamuelson commented on packages/unity-react-core/src/core/utils/index.js
> +export const initSidebarMenu = ({ targetSelector, props }) =>
All other exports are arranged in alpha order, let's keep to that pattern with this export, too, please.

2024-12-19 16:32 UTC, scott-williams-az requested changes

2024-12-19 16:32 UTC, scott-williams-az commented on packages/unity-react-core/examples/js/example-helper.js
> +                <a class="nav-link" href="sidebar-menu.html"><span class="fas fa-hand-spock"></span>SidebarMenu</a>
Bootstrap example only: Remove this change

2024-12-19 16:32 UTC, scott-williams-az commented on packages/unity-react-core/examples/sidebar-menu.html
> +<!DOCTYPE html>
Bootstrap example only: Remove this file

2024-12-19 16:32 UTC, scott-williams-az commented on packages/unity-react-core/src/components/SidebarMenu/SidebarMenu.tsx
> +                  <a
Wrap `a` tag with `GaEventWrapper`

2024-12-19 16:32 UTC, scott-williams-az commented on packages/unity-react-core/src/core/utils/index.js
>  import { List } from "../../components/List/List.tsx";
Bootstrap example only: Remove all changes in this file

2024-12-19 16:32 UTC, scott-williams-az commented on packages/unity-react-core/src/components/SidebarMenu/SidebarMenu.stories.tsx
> +      text: "Active Link",
I'd like to see which prop name we use more (various components use prop name `label` or `text` for link content)
We can discuss at a later time. Since this code is Bootstrap Example only it does not really matter at this point.

2025-01-09 15:54 UTC, mlsamuelson requested changes

2025-01-09 15:54 UTC, mlsamuelson commented on packages/unity-react-core/src/components/SidebarMenu/SidebarMenu.stories.tsx
> +export const Story2 = {
Why do we have Story 2? It renders identical to the main Sidebar story.  On the Docs page, they even react together - a click on one fires on the other.

2025-01-10 16:53 UTC, mlsamuelson approved these changes

2025-01-10 16:56 UTC, merged