UDS-1897: feat(component-carousel): added functionality to check screen width for modified perview value
ASU/asu-unity-stack pull request #1406
Opened 2024-11-14 17:12 UTC by juanmitriatti

Added functionality to check screen width for modified perview items value and to decide whether to show action buttons.

UDS-1897

### Description

### Links

- [JIRA ticket](https://asudev.jira.com/browse/UDS-1897)
- [Unity reference site](https://asu.github.io/asu-unity-stack/)
- [Unity Design Kit](https://shared-assets.adobe.com/link/fb14b288-bf63-47e0-5d30-384de5560455)

### FOR APPROVERS

- [Percy build approval](https://percy.io/5eae92d9/-all-UDS-packages)

2024-11-14 22:03 UTC, davidornelas11 requested changes

2024-11-14 22:03 UTC, davidornelas11 commented on packages/component-carousel/src/components/CardCarousel/index.js
> +          perViewValue = screenWidth > 1024 ? 3 : screenWidth > 768 ? 2 : 1;
Breaking this out to separate if, else statements will fix the build issue. We usually try to avoid nested ternaries. 
Ex: ```if (screenWidth > 1024) {
            perViewValue = 3;
            } else if (screenWidth > 768) {
            perViewValue = 2;
            } else {
            perViewValue = 1;
            }```

2024-11-14 22:03 UTC, davidornelas11 commented on packages/component-carousel/src/components/CardCarousel/index.js
> +        case "1":
This can be removed as the default will take care of everything not mentioned above

2024-11-15 17:42 UTC, davidornelas11 commented
Just another suggestion but not required, assigning the 1024 and 768 numbers to constants at the top of the file will make it a bit cleaner to read.

2024-11-15 17:58 UTC, juanmitriatti commented on packages/component-carousel/src/components/CardCarousel/index.js
> +          perViewValue = screenWidth > 1024 ? 3 : screenWidth > 768 ? 2 : 1;
Solved this build issue

2024-11-15 18:00 UTC, juanmitriatti commented on packages/component-carousel/src/components/CardCarousel/index.js
> +        case "1":
This `if` statement is necessary to render only one card on mobile when the carousel previously displayed two items per view.

2024-11-15 18:03 UTC, davidornelas11 commented on packages/component-carousel/src/components/CardCarousel/index.js
> +        case "1":
Sorry I think I commented on the wrong line, I meant the `case "1"` can be removed since the default is right under it and it's just gonna default if its not "2" or "3"

2024-11-15 18:30 UTC, juanmitriatti commented on packages/component-carousel/src/components/CardCarousel/index.js
> +        case "1":
I misunderstood. I thought you were referring to the second ternary case.

2024-11-15 18:35 UTC, juanmitriatti commented
> Just another suggestion but not required, assigning the 1024 and 768 numbers to constants at the top of the file will make it a bit cleaner to read.
Good suggestion, I added the constants

2024-11-21 17:23 UTC, mlsamuelson requested changes
Is this duplicating the code that's already set up to do this check? https://github.com/ASU/asu-unity-stack/blob/UDS-1897/packages/component-carousel/src/core/components/BaseCarousel/glide/glide.setup.js#L10-L40 ?

2024-11-21 18:03 UTC, juanmitriatti commented
> Is this duplicating the code that's already set up to do this check? https://github.com/ASU/asu-unity-stack/blob/UDS-1897/packages/component-carousel/src/core/components/BaseCarousel/glide/glide.setup.js#L10-L40 ?


Hi Michael,
They are different checks. One calculates how many cards are displayed, and the other calculates the carousel pages.

2024-11-21 18:57 UTC, mlsamuelson commented
@juanmitriatti Let's hold on this PR until we hear back from Kathy about the other Carousel issues.

2024-12-02 19:35 UTC, mlsamuelson approved these changes

2024-12-02 19:51 UTC, mlsamuelson commented
Approved. Once merged, we'll also need this change made in the `unity-react-core` package in the `component-consolidation` branch.

2024-12-02 21:10 UTC, davidornelas11 approved these changes
looks good

2024-12-02 21:10 UTC, merged