docs(unity-bootstrap-theme): added css and js for cookie consent
ASU/asu-unity-stack pull request #1407
Opened 2024-11-19 02:40 UTC by davidornelas11

No release needed as this initial addition is just to host it.
Read TODO's in code for more context on next steps

Testing steps:
1. Add the JS to any html page in a script tag.  This will initialize the banner
2. Manage cookies banner should be keyboard accessible. Descriptions should show and hide on keyboard selection
3. Styles should match Figma design closely.
If you do not have figma document, please reach out and I can share it

### FOR APPROVERS

- [Percy build approval](https://percy.io/5eae92d9/-all-UDS-packages)

2024-11-19 16:12 UTC, mlsamuelson requested changes

2024-11-19 16:12 UTC, mlsamuelson commented on README.md
> +The CSS for the cookie consent banner can be found in [unity-bootstrap-theme](./packages/unity-bootstrap-theme/src/css/cookie-consent.css). The JavaScript for the cookie consent banner can be found i
Link text says `component-cookie-consent` but the path is for `unity-bootstrap-theme` (which is where I'd want that to be).

2024-11-19 16:12 UTC, mlsamuelson commented on packages/unity-bootstrap-theme/src/css/cookie-consent.css
> +* TODO: Should we compile this css and include it in our css bundle or just import it and add it into a script in webspark?
I'd like to see this compiled and included in `dist/css/unity-bootstrap-theme.bundle.css`
as well as exported individually as `dist/css/-unity-consent.css` and have this documented ed in the [getting started docs](https://asu.github.io/asu-unity-stack/@asu/unity-bootstrap-theme/index.html?path=/docs/get-started-get-started--docs#-including-unity-in-your-project).

2024-11-19 16:12 UTC, mlsamuelson commented on packages/unity-bootstrap-theme/src/css/cookie-consent.css
> +* TODO: Should we compile this css and include it in our css bundle or just import it and add it into a script in webspark?
This could be a separate ticket to be completed later, if it'll be time-consuming to implement and is not immediately needed.

2024-11-19 16:12 UTC, mlsamuelson commented on packages/unity-bootstrap-theme/src/js/cookie-consent.js
> +      licenseKey: "55F4885B-41C9-4834-83F9-3924FCB2D7D3",
I'm guessing this matches code provided by the vendor and including the licenseKey in the frontend script is acceptable. Just putting this note here to confirm.

2024-11-19 16:24 UTC, davidornelas11 commented on packages/unity-bootstrap-theme/src/js/cookie-consent.js
> +      licenseKey: "55F4885B-41C9-4834-83F9-3924FCB2D7D3",
Yes from what I understand it’s a public key

2024-11-19 18:46 UTC, davidornelas11 commented on packages/unity-bootstrap-theme/src/css/cookie-consent.css
> +* TODO: Should we compile this css and include it in our css bundle or just import it and add it into a script in webspark?
Yea this would be easier done after component consolidation

2024-11-19 22:23 UTC, mlsamuelson requested changes
Need brand compliant focus ring on link and buttons. 
Need border fixed to match mockup on modal.

2024-11-19 22:25 UTC, mlsamuelson commented on packages/unity-bootstrap-theme/src/css/cookie-consent.css
> +* TODO: Should we compile this css and include it in our css bundle or just import it and add it into a script in webspark?
Will be done in [UDS-1903](https://asudev.jira.com/browse/UDS-1903) when ready to be widely and automatically deployed.

2024-11-20 00:16 UTC, mlsamuelson requested changes
Link focus is still missing.

2024-11-20 22:19 UTC, mlsamuelson approved these changes

2024-11-20 22:19 UTC, merged