UDS-1909: fix(app-webdir-ui): changed mailto and phone number aria-label
ASU/asu-unity-stack pull request #1411
Opened 2024-12-02 19:37 UTC by juanmitriatti

UDS-1909

Changed mailto and phone number aria-label

### Description

### Links

- [JIRA ticket](https://asudev.jira.com/browse/UDS-1909)
- [Unity reference site](https://asu.github.io/asu-unity-stack/)
- [Unity Design Kit](https://shared-assets.adobe.com/link/fb14b288-bf63-47e0-5d30-384de5560455)

### FOR APPROVERS

- [Percy build approval](https://percy.io/5eae92d9/-all-UDS-packages)

2024-12-04 23:06 UTC, mlsamuelson requested changes, later dismissed

2024-12-04 23:06 UTC, mlsamuelson commented on packages/app-webdir-ui/src/ProfileCard/index.js
> +                aria-label={`Mail to :${props.email.toLowerCase()}`}
We are no longer casting email addresses to lower case. Can you remove the `.toLowerCase()` ?

2024-12-05 17:08 UTC, juanmitriatti commented on packages/app-webdir-ui/src/ProfileCard/index.js
> +                aria-label={`Mail to :${props.email.toLowerCase()}`}
Solved

2024-12-17 17:00 UTC, scott-williams-az approved these changes

2025-01-06 18:49 UTC, merged