Schweb 1357 - Grid view
ASU/asu-unity-stack pull request #1418
Opened 2024-12-07 01:22 UTC by davidornelas11

Adding grid view for web directory as well as many accessibility fixes

### Links

- [SCHWEB-1357 main ticket](https://asudev.jira.com/browse/SCHWEB-1357))
- [mockups](https://xd.adobe.com/view/130f21d3-e62b-4425-b31a-5d32474de15c-465c/screen/164dd15c-73b8-46c4-91ae-223d9250d983/)

Accessibility tickets fixed in this:

- https://asudev.jira.com/browse/UDS-1844?atlOrigin=eyJpIjoiYzg0ZjhiMjkwOTc5NDJhOGJjN2FlYjFlM2NkYzcyNGYiLCJwIjoiaiJ9
- https://asudev.jira.com/browse/UDS-1845?atlOrigin=eyJpIjoiY2FlNzFkZjZlNGJmNDJkMzhhYTE1YTgwOTZhYjc2YjgiLCJwIjoiaiJ9
- https://asudev.jira.com/browse/UDS-1846?atlOrigin=eyJpIjoiNTUzODZkZTJkNDQzNDI4Mzk2MTRiZGIxNmE3ZjcyNjQiLCJwIjoiaiJ9

Also fixed 2 other issues:

- https://asudev.jira.com/browse/UDS-1911?atlOrigin=eyJpIjoiNzgzYTNhZGIyNTVlNDBhMzllOTk1MTAzMDI5NzkxZDgiLCJwIjoiaiJ9
- https://asudev.jira.com/browse/UDS-1902?atlOrigin=eyJpIjoiYWFkYWI3ZTJiZjY0NDJhMzhiMzM2YjYxOTBmZDdkNGEiLCJwIjoiaiJ9

### FOR APPROVERS

- [Percy build approval](https://percy.io/5eae92d9/-all-UDS-packages)

2024-12-09 15:57 UTC, scott-williams-az submitted a review, later dismissed
minor comments

2024-12-09 15:57 UTC, scott-williams-az commented on packages/app-webdir-ui/src/grid/grid.js
Follow pattern and rename file `src/Grid/index.js` I am fine with `src/Grid/Grid.js` since I perfect all my files are not names index

2024-12-09 15:57 UTC, scott-williams-az commented on packages/app-webdir-ui/src/grid/grid.js
> + * @param {string} props.className - Additional class name
Code handles undefined, so should these classNames props actually be optional

2024-12-09 15:57 UTC, scott-williams-az commented on packages/app-webdir-ui/src/grid/grid.js
> + * @param {number} props.gap - Bootstrap spacing (0-5)
`@param {0|1|2|3|4|5} props.gap - Bootstrap spacing (0-5)` typescript will warn if someone tries to pass in a 6

2024-12-09 21:54 UTC, mlsamuelson requested changes
As we discussed in our Zoom, 3 things:

Spacing between image and profile text should be 16px, and below the profile text to the next profile image the pacing should be 32px.

This commit has stories set to the grid view by default... let's only have one set to grid by default, so we can also verify and default behaviors.

Lastly, the Faculty Rank isn't working due to there currently being incomplete Faculty Rank data in QA. Let's point that story to the live site for now so we can validate.

2024-12-09 23:02 UTC, davidornelas11 commented on packages/app-webdir-ui/src/grid/grid.js
I'm confused, should I rename it to index.js?

2024-12-11 22:44 UTC, mlsamuelson approved these changes

2024-12-11 22:44 UTC, merged