chore(unity-react-core): add person profile story and component
ASU/asu-unity-stack pull request #1427
Opened 2024-12-19 00:24 UTC by davidornelas11

### Description
add person profile story

### Links

- [JIRA ticket](https://asudev.jira.com/browse/UDS-1877?atlOrigin=eyJpIjoiOWVlYTcyNTEyMTMwNGMyN2FjNmE3NzVmOTY2ZDhlYmUiLCJwIjoiaiJ9)

2024-12-19 16:20 UTC, scott-williams-az commented on packages/unity-react-core/src/components/PersonProfile/PersonProfile.tsx
> +              {...gaData}
remove line 114

2024-12-19 16:20 UTC, scott-williams-az commented on packages/unity-react-core/src/components/PersonProfile/PersonProfile.tsx
> +                <a
Wrap with `a` tag with `<GaEventWrapper>` and remove `data-ga-*` The <GaEventWrapper> will handle the attributes

2024-12-19 16:20 UTC, scott-williams-az commented on packages/unity-react-core/src/components/PersonProfile/PersonProfile.stories.tsx
> +import img from "../../assets/img/anon.png";
Can we try this out using the image in the shared folder: 
Replace: `"../../assets/img/anon.png" ;`
with: `"@shared/assets/img/named/anon.png";`
I can't remember if the `@shared` alias is working, use the long path if you have to
with: `"../../../../../shared/assets/img/named/anon.png";`

2025-01-10 17:54 UTC, mlsamuelson requested changes, later dismissed

2025-01-10 17:54 UTC, mlsamuelson commented on packages/unity-react-core/src/components/PersonProfile/PersonProfile.tsx
> +              {...gaData}
Does this `{...gaData}` line belong here when we also have the `gaData` prop?

2025-01-14 19:13 UTC, mlsamuelson approved these changes

2025-01-14 19:13 UTC, merged