test: percy setup and kitchen sink test pages
ASU/asu-unity-stack pull request #635
Opened 2021-11-18 20:01 UTC by nicolasBaudon

## Description

This pr contains the percy.io setup for the `component-carousel`, `app-degree-pages` and `app-rfi` packages with the corresponding kitchen sink test pages for each package as well.
I update the images where needed to make them consistent in every build.

2021-11-23 14:23 UTC, imorale2 submitted a review, later dismissed

2021-11-24 01:13 UTC, mlsamuelson approved these changes

2021-11-24 01:14 UTC, mlsamuelson requested changes
@nicolasBaudon This looks good. Can you resolve the conflicts? Then I'm happy to approve.

2021-11-24 15:54 UTC, mlsamuelson approved these changes
Approved. But not merging yet until we have a better sense of what's going on with Percy usage. This might push us over our limits. It can be merged once we have a plan.

2023-07-20 14:46 UTC, mlsamuelson commented
[Latest approach for Percy](https://github.com/ASU/asu-unity-stack/pull/971). Closing this.

2023-07-20 14:46 UTC, closed without merging