WS2-1171: Fix Partner logo ALT attribute.
ASU/asu-unity-stack pull request #662
Opened 2021-12-13 08:37 UTC by georgebaev

@nicolasBaudon @mlsamuelson this fixes the `alt` attribute of the Partner Logo section.

Ref.: https://asudev.jira.com/browse/WS2-1171?focusedCommentId=1393583 .

2021-12-13 13:20 UTC, mlsamuelson approved these changes

2021-12-13 13:51 UTC, nicolasBaudon submitted a review, later dismissed

2021-12-14 04:13 UTC, mlsamuelson approved these changes

2021-12-14 04:15 UTC, mlsamuelson requested changes
`Asu` should be `ASU`.

2022-11-30 16:29 UTC, mlsamuelson approved these changes

2023-02-01 20:25 UTC, merged

2023-02-01 20:25 UTC, mlsamuelson commented
Looks like this minor fix on the UDS side was approved but never merged.