fix(app-webdir-ui): fixed key errors on search results list component…
ASU/asu-unity-stack pull request #906
Opened 2022-12-14 00:35 UTC by davidornelas11

… and peopleIds error

2022-12-14 00:35 UTC, davidornelas11 commented
Ticket: https://asudev.jira.com/browse/UDS-1208?atlOrigin=eyJpIjoiZjQ1NWQ0ZDZlNTc2NDY2NDllMDFlYjkxMTEzY2Y2YmMiLCJwIjoiaiJ9

2022-12-14 18:14 UTC, maycomayco submitted a review, later dismissed
LGTM

2023-01-20 21:05 UTC, mlsamuelson requested changes
@davidornelas11 There is a conflict to resolve, and I'm thinking you're best positioned to evaluate the resolution.

2023-01-26 21:53 UTC, mlsamuelson approved these changes

2023-01-26 21:54 UTC, merged