feat(bootstrap4-theme): add image based card component
ASU/asu-unity-stack pull request #979
Opened 2023-02-28 15:24 UTC by maycomayco

![image](https://user-images.githubusercontent.com/1083822/221898712-ec7583b1-e084-42db-886a-e99dbe5af79f.png)
![image](https://user-images.githubusercontent.com/1083822/221898632-3fddb76c-705a-404b-beac-bef4b0eaf026.png)
![image](https://user-images.githubusercontent.com/1083822/221898653-323c7c39-5c62-41e9-af15-2c62d3f2f360.png)

2023-03-01 01:32 UTC, davidornelas11 requested changes

2023-03-01 01:32 UTC, davidornelas11 commented on packages/bootstrap4-theme/src/scss/extends/_cards.scss
> +      .hidden-details {
Should the hidden details be scrollable? Adding overflow: scroll to hidden-details fixes this but I'm not sure if that is the desired effect. Something to bring up in standup, maybe?

2023-03-01 14:26 UTC, maycomayco commented on packages/bootstrap4-theme/src/scss/extends/_cards.scss
> +      .hidden-details {
Good point to talk about in the standup today

2023-03-01 19:46 UTC, davidornelas11 submitted a review, later dismissed
Holding off on merging until Michael has some time to look it over as well

2023-05-25 16:46 UTC, closed without merging

2023-05-25 16:47 UTC, maycomayco commented
I closed this one because it was covered here https://github.com/ASU/asu-unity-stack/pull/1070