chore(bootstrap4-theme): remove dependency on design tokens
ASU/asu-unity-stack pull request #994
Opened 2023-03-24 18:09 UTC by scott-williams-az

Design Tokens created many very specific variables for components which were used once
Kept common variables used multiple times

no change to output: packages/bootstrap4-theme/dist/css/bootstrap-asu.css 

- [JIRA ticket](https://asudev.jira.com/browse/UDS-1278)

2023-03-24 21:39 UTC, maycomayco commented on packages/bootstrap4-theme/src/scss/extends/_alerts.scss
> +      opacity: 1;
I see that many variables were changed, and it seems that this is not expected since those variables belong to the ASU design guidelines. Maybe it was a mistake, could you check it?

2023-03-29 22:32 UTC, mlsamuelson commented on packages/bootstrap4-theme/src/scss/extends/_alerts.scss
> +      opacity: 1;
@maycomayco Are you saying that the calculated values have changed? What I see in the original design-tokens was that this specific value matches.

The overall approach matches my expectations for this task:
1. remove dependency on the design-tokens package
2. manage variables directly within the bootstrap package
3. avoid creating variables for single-use cases.

2023-03-29 22:54 UTC, mlsamuelson reviewed
This looks good and tests out for me.  I've not marked as "approved" yet because I don't want it to get merged until after we have the final release for the Webspark 2.9.0 release compiled.

2023-04-06 18:48 UTC, maycomayco commented on packages/bootstrap4-theme/src/scss/extends/_alerts.scss
> +      opacity: 1;
LGTM!

2023-04-18 18:25 UTC, mlsamuelson requested changes
Merge conflicts to resolve.

2023-05-01 20:38 UTC, mlsamuelson commented
Closing since we will be deprecating this component with the migration.

2023-05-01 20:38 UTC, closed without merging