feat(unity-bootstrap-theme): added html plugin
ASU/asu-unity-stack pull request #997
Opened 2023-03-28 22:17 UTC by davidornelas11

2023-03-29 16:07 UTC, scott-williams-az requested changes

2023-03-29 16:07 UTC, scott-williams-az commented on packages/unity-bootstrap-theme/.storybook/preview.js
> +    transform: (code) => {
regex '.*' vs '.*?'
<svg.*<\/svg>: will make 1 match "<svg></svg><svg></svg>"
<svg.*?<\/svg>: will make match all "<svg></svg>", "<svg></svg>"
consider:
    transform: (code) => {
      return (code
        .replace(/<svg.*?<\/svg>/g, "")
        .replace(/(<!--\s)(<span[^>]*?class=\"fas.*?><\/span>)(\s-->)/gi, "$2"));
    }

2023-03-29 16:07 UTC, scott-williams-az commented on packages/unity-bootstrap-theme/.storybook/preview.js
> +    root: ".row", // can be customized to wrap an element
I like the idea of adding a specific selector, like #html-root, this plugin will only match the first found selector so we should make it an id

2023-04-04 18:25 UTC, mlsamuelson commented on packages/unity-bootstrap-theme/.storybook/preview.js
> +    transform: (code) => {
Agree.

2023-04-05 21:31 UTC, merged